##########################################################################
# R code used to analize the results in 'gof-n50.RData'

# Library
library(memisc)

# reading RData file
load("gof-n50.RData")

se <- function(x) sd(x, na.rm = TRUE) / sqrt(length(x))

# Output
analysis <- array(0, dim = c(length(p), length(s), 5, 11, 2),
dimnames = list(p = p, s = s, gof = c("AIC", "BIC", "Fan_13", "GIC_aic", "GIC_bic"),
measures = c("value", "size", "TP", "FP", "TN", "FN", "TPR", "FPR", "FDR", "FNR", "F1"), summmary = c("mean", "se")))

i <- nsim
for(h in 1:length(p)){
	for(k in 1:length(s)){
		
		analysis[h, k, "AIC", "value", "mean"] <- mean(results[1:i, h, k, "AIC", "value"], na.rm = TRUE)
		analysis[h, k, "AIC", "value", "se"] <- se(results[1:i, h, k, "AIC", "value"])
		analysis[h, k, "AIC", "size", "mean"] <- median(results[1:i, h, k, "AIC", "size"], na.rm = TRUE)
		analysis[h, k, "AIC", "size", "se"] <- se(results[1:i, h, k, "AIC", "size"])
		analysis[h, k, "AIC", "TP", "mean"] <- mean(results[1:i, h, k, "AIC", "TP"], na.rm = TRUE)
		analysis[h, k, "AIC", "TP", "se"] <- se(results[1:i, h, k, "AIC", "TP"])
		analysis[h, k, "AIC", "FP", "mean"] <- mean(results[1:i, h, k, "AIC", "FP"], na.rm = TRUE)
		analysis[h, k, "AIC", "FP", "se"] <- se(results[1:i, h, k, "AIC", "FP"])
		analysis[h, k, "AIC", "TN", "mean"] <- mean(results[1:i, h, k, "AIC", "TN"], na.rm = TRUE)
		analysis[h, k, "AIC", "TN", "se"] <- se(results[1:i, h, k, "AIC", "TN"])
		analysis[h, k, "AIC", "FN", "mean"] <- mean(results[1:i, h, k, "AIC", "FN"], na.rm = TRUE)
		analysis[h, k, "AIC", "FN", "se"] <- se(results[1:i, h, k, "AIC", "FN"])
		analysis[h, k, "AIC", "TPR", "mean"] <- mean(results[1:i, h, k, "AIC", "TPR"], na.rm = TRUE)
		analysis[h, k, "AIC", "TPR", "se"] <- se(results[1:i, h, k, "AIC", "TPR"])
		analysis[h, k, "AIC", "FPR", "mean"] <- mean(results[1:i, h, k, "AIC", "FPR"], na.rm = TRUE)
		analysis[h, k, "AIC", "FPR", "se"] <- se(results[1:i, h, k, "AIC", "FPR"])
		analysis[h, k, "AIC", "FDR", "mean"] <- mean(results[1:i, h, k, "AIC", "FDR"], na.rm = TRUE)
		analysis[h, k, "AIC", "FDR", "se"] <- se(results[1:i, h, k, "AIC", "FDR"])
		analysis[h, k, "AIC", "FNR", "mean"] <- mean(results[1:i, h, k, "AIC", "FNR"], na.rm = TRUE)
		analysis[h, k, "AIC", "FNR" ,"se"] <- se(results[1:i, h, k, "AIC", "FNR"])
		analysis[h, k, "AIC", "F1", "mean"] <- mean(results[1:i, h, k, "AIC", "F1"], na.rm = TRUE)
		analysis[h, k, "AIC", "F1", "se"] <- se(results[1:i, h, k, "AIC", "F1"])
		
		analysis[h, k, "BIC", "value", "mean"] <- mean(results[1:i, h, k, "BIC", "value"], na.rm = TRUE)
		analysis[h, k, "BIC", "value", "se"] <- se(results[1:i, h, k, "BIC", "value"])
		analysis[h, k, "BIC", "size", "mean"] <- median(results[1:i, h, k, "BIC", "size"], na.rm = TRUE)
		analysis[h, k, "BIC", "size", "se"] <- se(results[1:i, h, k, "BIC", "size"])
		analysis[h, k, "BIC", "TP", "mean"] <- mean(results[1:i, h, k, "BIC", "TP"], na.rm = TRUE)
		analysis[h, k, "BIC", "TP", "se"] <- se(results[1:i, h, k, "BIC", "TP"])
		analysis[h, k, "BIC", "FP", "mean"] <- mean(results[1:i, h, k, "BIC", "FP"], na.rm = TRUE)
		analysis[h, k, "BIC", "FP", "se"] <- se(results[1:i, h, k, "BIC", "FP"])
		analysis[h, k, "BIC", "TN", "mean"] <- mean(results[1:i, h, k, "BIC", "TN"], na.rm = TRUE)
		analysis[h, k, "BIC", "TN", "se"] <- se(results[1:i, h, k, "BIC", "TN"])
		analysis[h, k, "BIC", "FN", "mean"] <- mean(results[1:i, h, k, "BIC", "FN"], na.rm = TRUE)
		analysis[h, k, "BIC", "FN", "se"] <- se(results[1:i, h, k, "BIC", "FN"])
		analysis[h, k, "BIC", "TPR", "mean"] <- mean(results[1:i, h, k, "BIC", "TPR"], na.rm = TRUE)
		analysis[h, k, "BIC", "TPR", "se"] <- se(results[1:i, h, k, "BIC", "TPR"])
		analysis[h, k, "BIC", "FPR", "mean"] <- mean(results[1:i, h, k, "BIC", "FPR"], na.rm = TRUE)
		analysis[h, k, "BIC", "FPR", "se"] <- se(results[1:i, h, k, "BIC", "FPR"])
		analysis[h, k, "BIC", "FDR", "mean"] <- mean(results[1:i, h, k, "BIC", "FDR"], na.rm = TRUE)
		analysis[h, k, "BIC", "FDR", "se"] <- se(results[1:i, h, k, "BIC", "FDR"])
		analysis[h, k, "BIC", "FNR", "mean"] <- mean(results[1:i, h, k, "BIC", "FNR"], na.rm = TRUE)
		analysis[h, k, "BIC", "FNR", "se"] <- se(results[1:i, h, k, "BIC", "FNR"])
		analysis[h, k, "BIC", "F1", "mean"] <- mean(results[1:i, h, k, "BIC", "F1"], na.rm = TRUE)
		analysis[h, k, "BIC", "F1", "se"] <- se(results[1:i, h, k, "BIC", "F1"])
		
		analysis[h, k, "Fan_13", "value", "mean"] <- mean(results[1:i, h, k, "Fan_13", "value"], na.rm = TRUE)
		analysis[h, k, "Fan_13", "value", "se"] <- se(results[1:i, h, k, "Fan_13", "value"])
		analysis[h, k, "Fan_13", "size", "mean"] <- median(results[1:i, h, k, "Fan_13", "size"], na.rm = TRUE)
		analysis[h, k, "Fan_13", "size", "se"] <- se(results[1:i, h, k, "Fan_13", "size"])
		analysis[h, k, "Fan_13", "TP", "mean"] <- mean(results[1:i, h, k, "Fan_13", "TP"], na.rm = TRUE)
		analysis[h, k, "Fan_13", "TP", "se"] <- se(results[1:i, h, k, "Fan_13", "TP"])
		analysis[h, k, "Fan_13", "FP", "mean"] <- mean(results[1:i, h, k, "Fan_13", "FP"], na.rm = TRUE)
		analysis[h, k, "Fan_13", "FP", "se"] <- se(results[1:i, h, k, "Fan_13", "FP"])
		analysis[h, k, "Fan_13", "TN", "mean"] <- mean(results[1:i, h, k, "Fan_13", "TN"], na.rm = TRUE)
		analysis[h, k, "Fan_13", "TN", "se"] <- se(results[1:i, h, k, "Fan_13", "TN"])
		analysis[h, k, "Fan_13", "FN", "mean"] <- mean(results[1:i, h, k, "Fan_13", "FN"], na.rm = TRUE)
		analysis[h, k, "Fan_13", "FN", "se"] <- se(results[1:i, h, k, "Fan_13", "FN"])
		analysis[h, k, "Fan_13", "TPR", "mean"] <- mean(results[1:i, h, k, "Fan_13", "TPR"], na.rm = TRUE)
		analysis[h, k, "Fan_13", "TPR", "se"] <- se(results[1:i, h, k, "Fan_13", "TPR"])
		analysis[h, k, "Fan_13", "FPR", "mean"] <- mean(results[1:i, h, k, "Fan_13", "FPR"], na.rm = TRUE)
		analysis[h, k, "Fan_13", "FPR", "se"] <- se(results[1:i, h, k, "Fan_13", "FPR"])
		analysis[h, k, "Fan_13", "FDR", "mean"] <- mean(results[1:i, h, k, "Fan_13", "FDR"], na.rm = TRUE)
		analysis[h, k, "Fan_13", "FDR", "se"] <- se(results[1:i, h, k, "Fan_13", "FDR"])
		analysis[h, k, "Fan_13", "FNR", "mean"] <- mean(results[1:i, h, k, "Fan_13", "FNR"], na.rm = TRUE)
		analysis[h, k, "Fan_13", "FNR", "se"] <- se(results[1:i, h, k, "Fan_13", "FNR"])
		analysis[h, k, "Fan_13", "F1", "mean"] <- mean(results[1:i, h, k, "Fan_13", "F1"], na.rm = TRUE)
		analysis[h, k, "Fan_13", "F1", "se"] <- se(results[1:i, h, k, "Fan_13", "F1"])
		
		analysis[h, k, "GIC_aic", "value", "mean"] <- mean(results[1:i, h, k, "GIC_aic", "value"], na.rm = TRUE)
		analysis[h, k, "GIC_aic", "value", "se"] <- se(results[1:i, h, k, "GIC_aic", "value"])
		analysis[h, k, "GIC_aic", "size", "mean"] <- median(results[1:i, h, k, "GIC_aic", "size"], na.rm = TRUE)
		analysis[h, k, "GIC_aic", "size", "se"] <- se(results[1:i, h, k, "GIC_aic", "size"])
		analysis[h, k, "GIC_aic", "TP", "mean"] <- mean(results[1:i, h, k, "GIC_aic", "TP"], na.rm = TRUE)
		analysis[h, k, "GIC_aic", "TP", "se"] <- se(results[1:i, h, k, "GIC_aic", "TP"])
		analysis[h, k, "GIC_aic", "FP", "mean"] <- mean(results[1:i, h, k, "GIC_aic", "FP"], na.rm = TRUE)
		analysis[h, k, "GIC_aic", "FP", "se"] <- se(results[1:i, h, k, "GIC_aic", "FP"])
        	analysis[h, k, "GIC_aic", "TN", "mean"] <- mean(results[1:i, h, k, "GIC_aic", "TN"], na.rm = TRUE)
		analysis[h, k, "GIC_aic", "TN", "se"] <- se(results[1:i, h, k, "GIC_aic", "TN"])
		analysis[h, k, "GIC_aic", "FN", "mean"] <- mean(results[1:i, h, k, "GIC_aic", "FN"], na.rm = TRUE)
		analysis[h, k, "GIC_aic", "FN", "se"] <- se(results[1:i, h, k, "GIC_aic", "FN"])
		analysis[h, k, "GIC_aic", "TPR", "mean"] <- mean(results[1:i, h, k, "GIC_aic", "TPR"], na.rm = TRUE)
		analysis[h, k, "GIC_aic", "TPR", "se"] <- se(results[1:i, h, k, "GIC_aic", "TPR"])
		analysis[h, k, "GIC_aic", "FPR", "mean"] <- mean(results[1:i, h, k, "GIC_aic", "FPR"], na.rm = TRUE)
		analysis[h, k, "GIC_aic", "FPR", "se"] <- se(results[1:i, h, k, "GIC_aic", "FPR"])
		analysis[h, k, "GIC_aic", "FDR", "mean"] <- mean(results[1:i, h, k, "GIC_aic", "FDR"], na.rm = TRUE)
		analysis[h, k, "GIC_aic", "FDR", "se"] <- se(results[1:i, h, k, "GIC_aic", "FDR"])
		analysis[h, k, "GIC_aic", "FNR", "mean"] <- mean(results[1:i, h, k, "GIC_aic", "FNR"], na.rm = TRUE)
		analysis[h, k, "GIC_aic", "FNR", "se"] <- se(results[1:i, h, k, "GIC_aic", "FNR"])
		analysis[h, k, "GIC_aic", "F1", "mean"] <- mean(results[1:i, h, k, "GIC_aic", "F1"], na.rm = TRUE)
		analysis[h, k, "GIC_aic", "F1", "se"] <- se(results[1:i, h, k, "GIC_aic", "F1"])
	  
		analysis[h, k, "GIC_bic", "value", "mean"] <- mean(results[1:i, h, k, "GIC_bic", "value"], na.rm = TRUE)
		analysis[h, k, "GIC_bic", "value", "se"] <- se(results[1:i, h, k, "GIC_bic", "value"])
		analysis[h, k, "GIC_bic", "size", "mean"] <- median(results[1:i, h, k, "GIC_bic", "size"], na.rm = TRUE)
		analysis[h, k, "GIC_bic", "size", "se"] <- se(results[1:i, h, k, "GIC_bic", "size"])
		analysis[h, k, "GIC_bic", "TP", "mean"] <- mean(results[1:i, h, k, "GIC_bic", "TP"], na.rm = TRUE)
		analysis[h, k, "GIC_bic", "TP", "se"] <- se(results[1:i, h, k, "GIC_bic", "TP"])
		analysis[h, k, "GIC_bic", "FP", "mean"] <- mean(results[1:i, h, k, "GIC_bic", "FP"], na.rm = TRUE)
		analysis[h, k, "GIC_bic", "FP", "se"] <- se(results[1:i, h, k, "GIC_bic", "FP"])
		analysis[h, k, "GIC_bic", "TN", "mean"] <- mean(results[1:i, h, k, "GIC_aic", "TN"], na.rm = TRUE)
		analysis[h, k, "GIC_bic", "TN", "se"] <- se(results[1:i, h, k, "GIC_aic", "TN"])
		analysis[h, k, "GIC_bic", "FN", "mean"] <- mean(results[1:i, h, k, "GIC_aic", "FN"], na.rm = TRUE)
		analysis[h, k, "GIC_bic", "FN", "se"] <- se(results[1:i, h, k, "GIC_aic", "FN"])
		analysis[h, k, "GIC_bic", "TPR", "mean"] <- mean(results[1:i, h, k, "GIC_aic", "TPR"], na.rm = TRUE)
		analysis[h, k, "GIC_bic", "TPR", "se"] <- se(results[1:i, h, k, "GIC_aic", "TPR"])
		analysis[h, k, "GIC_bic", "FPR", "mean"] <- mean(results[1:i, h, k, "GIC_aic", "FPR"], na.rm = TRUE)
		analysis[h, k, "GIC_bic", "FPR", "se"] <- se(results[1:i, h, k, "GIC_aic", "FPR"])
		analysis[h, k, "GIC_bic", "FDR", "mean"] <- mean(results[1:i, h, k, "GIC_aic", "FDR"], na.rm = TRUE)
		analysis[h, k, "GIC_bic", "FDR", "se"] <- se(results[1:i, h, k, "GIC_aic", "FDR"])
		analysis[h, k, "GIC_bic", "FNR", "mean"] <- mean(results[1:i, h, k, "GIC_aic", "FNR"], na.rm = TRUE)
		analysis[h, k, "GIC_bic", "FNR", "se"] <- se(results[1:i, h, k, "GIC_aic", "FNR"])
		analysis[h, k, "GIC_bic", "F1", "mean"] <- mean(results[1:i, h, k, "GIC_aic", "F1"], na.rm = TRUE)
		analysis[h, k, "GIC_bic", "F1", "se"] <- se(results[1:i, h, k, "GIC_aic", "F1"])
    }
}

analysis.tbl <- as.table(analysis)
New_tab <- round(ftable(analysis.tbl[, , , c("size", "FPR", "FDR", "FNR", "F1"), ], row.vars = c("p", "s", "gof"), col.vars = c("measures", "summmary")), 3)
New_tab

toLatex(New_tab, digits = 3)
